In [2]:
arr = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
length(arr)

3

In [4]:
eltype(arr)

Int64

In [2]:
arr2=[1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [3]:
zeros(Int, 4, 6)

4×6 Matrix{Int64}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [4]:
collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [5]:
[m+n for n=1:8,m=1:8]

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

In [6]:
x=collect(1:2:13)

7-element Vector{Int64}:
  1
  3
  5
  7
  9
 11
 13

In [7]:
A=[i+j for i=1:4,j=1:5]

4×5 Matrix{Int64}:
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8
 5  6  7  8  9

In [8]:
A[:,1:2:5]

4×3 Matrix{Int64}:
 2  4  6
 3  5  7
 4  6  8
 5  7  9

In [9]:
A[1:2,[5,3,2]]

2×3 Matrix{Int64}:
 6  4  3
 7  5  4

In [10]:
A=[1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [11]:
B=[1 3 5; 2 4 6]

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

In [12]:
A+B

2×3 Matrix{Int64}:
 2  5   8
 6  9  12

In [13]:
B-A

2×3 Matrix{Int64}:
  0   1  2
 -2  -1  0

In [14]:
A .* B

2×3 Matrix{Int64}:
 1   6  15
 8  20  36

In [15]:
sqrt.(A)

2×3 Matrix{Float64}:
 1.0  1.41421  1.73205
 2.0  2.23607  2.44949

In [16]:
A=[3,2,1,4,8,6,5]

7-element Vector{Int64}:
 3
 2
 1
 4
 8
 6
 5

In [17]:
sort(A)

7-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 8

In [19]:
A=collect(1:2:11)

6-element Vector{Int64}:
  1
  3
  5
  7
  9
 11

In [20]:
insert!(A,3,15)

7-element Vector{Int64}:
  1
  3
 15
  5
  7
  9
 11

In [1]:
A=collect(1:2:13);print(splice!(A,3:4))

[5, 7]

In [2]:
A

5-element Vector{Int64}:
  1
  3
  9
 11
 13

In [5]:
A=collect(1:2:11)
x = splice!(A,2)
A

5-element Vector{Int64}:
  1
  5
  7
  9
 11

In [8]:
A=collect(1:2:11)
B=splice!(A,3:2,[11,12,13,14])
A

10-element Vector{Int64}:
  1
  3
 11
 12
 13
 14
  5
  7
  9
 11

In [10]:
A=collect(1:2:11)
x = splice!(A,3,4)

5

In [11]:
A

6-element Vector{Int64}:
  1
  3
  4
  7
  9
 11

In [14]:
A=collect(1:2:11)
splice!(A,3,[-1,-2,-3])
A

8-element Vector{Int64}:
  1
  3
 -1
 -2
 -3
  7
  9
 11

In [5]:
x=collect(1:6)

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [6]:
join(x, ", ")

"1, 2, 3, 4, 5, 6"

In [7]:
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

7-element Vector{String}:
 "Monday"
 "Tuesday"
 "Wednesday"
 "Thursday"
 "Friday"
 "Saturday"
 "Sunday"

In [8]:
join(days, ", ", " and ")

"Monday, Tuesday, Wednesday, Thursday, Friday, Saturday and Sunday"

In [1]:
str = "1; 2; 3; 4; 5; 6"

"1; 2; 3; 4; 5; 6"

In [3]:
split(str, "; ")

6-element Vector{SubString{String}}:
 "1"
 "2"
 "3"
 "4"
 "5"
 "6"

In [4]:
map(s-> parse(Int,s), split(str, "; "))

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [3]:
(1,2,3) .+ (4,5,6)

(5, 7, 9)

In [4]:
[1,2,3] .+ 10

3-element Vector{Int64}:
 11
 12
 13